# Generated by Django 5.0.6 on 2025-05-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degusta_rioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='id_comentario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='id_restaurante',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_user',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
