# Generated by Django 5.0.6 on 2025-05-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degusta_rioApp', '0002_alter_comentario_id_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_restaurante/'),
        ),
    ]
