# Generated by Django 5.1.1 on 2025-06-15 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degusta_rioApp', '0004_restaurante_avaliacao_restaurante_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='avaliacao',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='AvaliacaoRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrelas', models.PositiveSmallIntegerField(choices=[(1, '1 Estrela'), (2, '2 Estrelas'), (3, '3 Estrelas'), (4, '4 Estrelas'), (5, '5 Estrelas')])),
                ('comentario', models.TextField(blank=True, max_length=500)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='degusta_rioApp.restaurante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degusta_rioApp.usuario')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'unique_together': {('restaurante', 'usuario')},
            },
        ),
    ]
