# Generated by Django 5.1.1 on 2025-06-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degusta_rioApp', '0005_alter_restaurante_avaliacao_avaliacaorestaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='avaliacao',
            field=models.FloatField(null=True),
        ),
    ]
