# Generated by Django 5.1.1 on 2025-06-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degusta_rioApp', '0006_alter_restaurante_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='preco',
            field=models.CharField(choices=[('$', '$ - Econômico'), ('$$', '$$ - Moderado'), ('$$$', '$$$ - Caro')], default='$$', max_length=3, verbose_name='Faixa de Preço'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='avaliacao',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
