# Generated by Django 5.1.1 on 2025-06-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degusta_rioApp', '0007_restaurante_preco_alter_restaurante_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='avaliacao',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
